name: fortest
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.1 <4.0.0'

dependencies:
  english_words: ^4.0.0
  flutter:
    sdk: flutter
  go_router: ^12.1.1
  image: ^4.1.3
  image_picker: ^1.0.4
  file_picker: ^4.0.10
  flutter_screenutil: ^5.9.0

  shared_preferences: ^2.0.13

  tflite_flutter: ^0.9.1
  palette_generator: ^0.3.3+3
  color: ^3.0.0
  path_provider: ^2.0.15

  cupertino_icons: ^1.0.2
  firebase_core: ^2.24.0
  cloud_firestore: ^4.13.3
  firebase_storage: ^11.5.3
  firebase_in_app_messaging: ^0.7.4+6
  firebase_auth: ^4.15.0
  firebase_app_check: ^0.2.1+6

  flutter_naver_map: ^1.0.2

  geolocator: ^10.1.0
  geocoding: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/model_with_metadata.tflite
    - assets/image/
    - assets/image/logo.png
    - assets/image/logo_onlyimg.png
  fonts:
    - family: s-core
      fonts:
        - asset: assets/font/s-core/SCDream1.otf
        - asset: assets/font/s-core/SCDream2.otf
        - asset: assets/font/s-core/SCDream3.otf
        - asset: assets/font/s-core/SCDream4.otf
        - asset: assets/font/s-core/SCDream5.otf
        - asset: assets/font/s-core/SCDream6.otf
        - asset: assets/font/s-core/SCDream7.otf
        - asset: assets/font/s-core/SCDream8.otf
        - asset: assets/font/s-core/SCDream9.otf
