name: fortest
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.1 <4.0.0'

dependencies:
  english_words: ^4.0.0
  flutter:
    sdk: flutter
  go_router: ^12.1.1
  image: ^4.1.3
  image_picker: ^1.0.4
  file_picker: ^4.0.10
  flutter_screenutil: ^5.9.0

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
